Bug fix: AggregateTemplateBuilder is even more generics heavy now. new ChildBuildDirective type 3 in AggregateTemplateBuilder to support changes in method MmTemplate#createInterestTradeLegBuildDirective
java.lang.NullPointerException: Cannot invoke "io.alw.css.domain.trade.TradeLeg.valueDate()" because the return value of "io.alw.css.tradepublisher.trade.template.domain.InterestTradeLeg.interestLeg()" is null
	at io.alw.css.tradepublisher.trade.template.MmTemplate.lambda$buildAmendmentContextForCommonAmendEvents$1(MmTemplate.java:183)