NPE fix
java.lang.NullPointerException: Cannot invoke "io.alw.css.domain.trade.TradeLeg.tradeLegId()" because "from" is null
	at io.alw.css.domain.trade.TradeLegBuilder.builder(TradeLegBuilder.java:102)
	at io.alw.css.fosimulator.template.CashMessageAmendmentTemplate.lambda$handleTradeRebookEvent$1(CashMessageAmendmentTemplate.java:138)